spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL:localhost}:3306/${DB_NAME:jugan}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&tinyInt1isBit=false&rewriteBatchedStatements=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}

  jpa:
    hibernate:
      ddl-auto: ${DDL:update}
    properties.hibernate:
      format_sql: true
      show_sql: ${SHOW_SQL:true}
      jdbc:
        batch_size: 200
  jackson:
    property-naming-strategy: SNAKE_CASE
